name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use these flags '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: CLI Version
      description: Run `asset-generator --version` to get the version
      placeholder: v0.1.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: Run `go version` to get the version
      placeholder: go1.21.0
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Ubuntu 22.04, macOS 13.0, Windows 11
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remember to redact sensitive information)
      placeholder: Paste your config file or relevant flags
      render: yaml
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant log output (run with -v for verbose logs)
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
    validations:
      required: false
