# Example configuration file for Asset Generator CLI

# SwarmUI API endpoint
api-url: http://localhost:7801

# API authentication (optional)
# api-key: your-api-key-here

# Default output format (table, json, yaml)
format: table

# Verbosity settings
verbose: false
quiet: false

# Default generation parameters
generate:
  model: stable-diffusion-xl
  steps: 20
  width: 512
  length: 512  # Note: 'height' also supported as alias
  cfg-scale: 7.5
  sampler: euler_a
  
  # SkimmedCFG (Distilled CFG) settings - advanced sampling technique
  # Enables improved quality and faster generation with compatible models
  # skimmed-cfg: false
  # skimmed-cfg-scale: 3.0      # Typically lower than standard CFG
  # skimmed-cfg-start: 0.0      # Start applying at 0% (0.0-1.0)
  # skimmed-cfg-end: 1.0        # Stop applying at 100% (0.0-1.0)
